### ISSUE TITLE
Still a few bad time values in USGS data

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#143]
There was no data in 1960 or in 2037.

It look like these two Monterey canyon station have bad time values: 
![2016-01-27_15-42-50](https://cloud.githubusercontent.com/assets/1872600/12627614/d767ffa8-c50c-11e5-80be-baf059cbe319.jpg)
![2016-01-27_15-45-09](https://cloud.githubusercontent.com/assets/1872600/12627663/15fb15c0-c50d-11e5-952b-9f6d08d16f9f.jpg)

@emontgomery-usgs  how should we fix these?

**Comment by emontgomery-usgs** [comment]
Seems like as they come up we should repair the original data, so if a new
conversion to CF is needed, we won't have to repair the resulting data
again.

On Wed, Jan 27, 2016 at 3:46 PM, Rich Signell <notifications@github.com>
wrote:

> There was no data in 1960 or in 2037.
>
> It look like these two Monterey canyon station have bad time values:
> [image: 2016-01-27_15-42-50]
> <https://cloud.githubusercontent.com/assets/1872600/12627614/d767ffa8-c50c-11e5-80be-baf059cbe319.jpg>
> [image: 2016-01-27_15-45-09]
> <https://cloud.githubusercontent.com/assets/1872600/12627663/15fb15c0-c50d-11e5-952b-9f6d08d16f9f.jpg>
>
> @emontgomery-usgs <https://github.com/emontgomery-usgs> how should we fix
> these?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/143>.
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by rsignell-usgs** [comment]
@emontgomery-usgs, okay, please correct at your convenience and let us know.

**Comment by emontgomery-usgs** [comment]
@rsignell-usgs

This is odd- I can't find anything wrong with time in the data files.  The
Monterey canyon data on stellwagen does not appear to have any wonky times
in it.   I also checked the files on geoport that populate the portal, and
they too appear to have all clean times, with no outliers or missing values.

Based on the depths in the plots, the files in question are 4231-a.cdf,
4231att-a.cdf, and 4261a-cdf (these are the only ones that have temperature
at the depths indicated).

Perhaps the portal experts can check and see if something strange happens
after it's harvested from the TDS?

On Wed, Jan 27, 2016 at 4:07 PM, Rich Signell <notifications@github.com>
wrote:

> @emontgomery-usgs <https://github.com/emontgomery-usgs>, okay, please
> correct at your convenience and let us know.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/143#issuecomment-175852667>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by rsignell-usgs** [comment]
@emontgomery-usgs , indeed the problem seems not to be on our end.    Even when you click on the "parameter info" in the portal, it shows a start date of 1993.   Yet the plot shows start of 1960.   I think something is wrong on the Axiom side.    @kwilcox ?

![2016-01-28_11-50-15](https://cloud.githubusercontent.com/assets/1872600/12651694/9d28fc44-c5b5-11e5-8c18-36db7b037a84.jpg)

**Comment by kwilcox** [comment]
I'll take a look at the CF files on our end

**Comment by kwilcox** [comment]
Fixed, please review!

**Comment by emontgomery-usgs** [comment]
Just now, the link to the oceanographic observations goes here:
http://cmgdata.usgsportals.net/#module-metadata/590b5a22-b61e-11e4-b2db-00265529168c/6878f136-b61e-11e4-a8f5-00265529168c,
and it doesn't work at all.  No site icons appear, and the grey box isn't
populated.  Ctrl-F5 doesn't fix it.

I can't review it if I can't see it.  Sorry!

On Wed, Feb 24, 2016 at 2:01 PM, Kyle Wilcox <notifications@github.com>
wrote:

> Fixed, please review!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/143#issuecomment-188406956>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by kwilcox** [comment]
hmmm its working for me!  I'm updating a bunch of other issues now as well so putting off checking might be beneficial!

**Comment by emontgomery-usgs** [comment]
This error isn't new- I noticed it Monday and sent you email then.  Hadn't
tried to use the site in a while, so don't know how much longer it's had
issues.

On Wed, Feb 24, 2016 at 2:23 PM, Kyle Wilcox <notifications@github.com>
wrote:

> hmmm its working for me! I'm updating a bunch of other issues now as well
> so putting off checking might be beneficial!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/143#issuecomment-188416513>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by kwilcox** [comment]
@rsignell-usgs can you try the site? http://cmgdata.usgsportals.net/#module-metadata/590b5a22-b61e-11e4-b2db-00265529168c/6878f136-b61e-11e4-a8f5-00265529168c

**Comment by rsignell-usgs** [comment]
Yes, the URL works for me.   But we still have problems with two Monterey Bay stations.   Although this data was collected in 1993-1994, the metadata for Mooring 423 has a start time in 1965, and Mooring 242 has a stop time in 2023:

![2016-02-24_16-22-33](https://cloud.githubusercontent.com/assets/1872600/13301632/e473ec80-db13-11e5-95c1-90eb376be053.png)
![2016-02-24_16-24-30](https://cloud.githubusercontent.com/assets/1872600/13301638/e9cfff5c-db13-11e5-9d35-6d4cdebf2e12.png)

**Comment by rsignell-usgs** [comment]
http://cmgdata.usgsportals.net/#module-metadata/590b5a22-b61e-11e4-b2db-00265529168c/6878f136-b61e-11e4-a8f5-00265529168c

**Comment by kwilcox** [comment]
@rsignell-usgs I think I get to blame you for this one!

https://github.com/USGS-CMG/usgs-cmg-portal/blob/master/woods_hole_obs_data/collect.py#L371-L372

The values are coming out wrong from that line. I'll dig into it...

**Comment by emontgomery-usgs** [comment]
I still can't see the portal on chrome Version 39.0.2171.71.  I am not
allowed to update Chrome either due to DOI policy

I tried with IE and get the same problem with no site markers and nothing
in the grey search box, except the whirly circle.  I'm on the WHSC network-
I'll try from home to see if it has something to do with being on the WHSC
network.


On Wed, Feb 24, 2016 at 4:31 PM, Rich Signell <notifications@github.com>
wrote:

>
> http://cmgdata.usgsportals.net/#module-metadata/590b5a22-b61e-11e4-b2db-00265529168c/6878f136-b61e-11e4-a8f5-00265529168c
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/143#issuecomment-188460936>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by kwilcox** [comment]
@emontgomery-usgs  @rthieler-usgs  This bad time data is actually in the raw files.  The good news is that it only occurs in the `MONTEREY_CAN` project.  It's a bit tricky to find, but here are the offending indexes in one particular file

http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/Data/MONTEREY_CAN/4232-a.cdf.ascii?time[5110:1:5190]

You can see it jumps from `2449257` to `2465116` (**15859 days!!**), then back down to `2449257`.

**Comment by emontgomery-usgs** [comment]
Will get on fixing that tomrrow AM.

On Wed, Feb 24, 2016 at 6:15 PM, Kyle Wilcox <notifications@github.com>
wrote:

> @emontgomery-usgs <https://github.com/emontgomery-usgs> @rthieler-usgs
> <https://github.com/rthieler-usgs> This bad time data is actually in the
> raw files. The good news is that it only occurs in the MONTEREY_CAN
> project. It's a bit tricky to find, but here are the offending indexes in
> one particular file
>
>
> http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/Data/MONTEREY_CAN/4232-a.cdf.ascii?time[5110:1:5190]
>
> You can see it jumps from 2449257 to 2465116 (*15859 days!!*), then back
> down to 2449257.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/143#issuecomment-188508497>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by emontgomery-usgs** [comment]
Kyle,

I don't know why the time series part of the portal is not working for me,
but I tried IE and Chrome from home, and I still get the cyling loopy thing
and no data displayed.

Sorry!

On Wed, Feb 24, 2016 at 5:07 PM, Montgomery, Ellyn <emontgomery@usgs.gov>
wrote:

> I still can't see the portal on chrome Version 39.0.2171.71.  I am not
> allowed to update Chrome either due to DOI policy
>
> I tried with IE and get the same problem with no site markers and nothing
> in the grey search box, except the whirly circle.  I'm on the WHSC network-
> I'll try from home to see if it has something to do with being on the WHSC
> network.
>
>
> On Wed, Feb 24, 2016 at 4:31 PM, Rich Signell <notifications@github.com>
> wrote:
>
>>
>> http://cmgdata.usgsportals.net/#module-metadata/590b5a22-b61e-11e4-b2db-00265529168c/6878f136-b61e-11e4-a8f5-00265529168c
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/143#issuecomment-188460936>
>> .
>>
>
>
>
> --
> Ellyn Montgomery, Oceanographer and Data Manager
> U.S. Geological Survey
> Woods Hole Coastal and Marine Science Center
> 384 Woods Hole Rd., Woods Hole, MA, 02543-1598
> (508) 457-2356
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by rsignell-usgs** [comment]
I just tried this URL again: 
http://cmgdata.usgsportals.net/#module-metadata/590b5a22-b61e-11e4-b2db-00265529168c/6878f136-b61e-11e4-a8f5-00265529168c

and I think I see what @emontgomery-usgs is talking about.  I get the empty map below on both chrome and firefox, even after clearing cookies and refreshing:
![2016-02-24_19-04-24](https://cloud.githubusercontent.com/assets/1872600/13305551/ecc62cc0-db29-11e5-9202-5e92cdbe2381.jpg)

**Comment by emontgomery-usgs** [comment]
Thank you for duplicating the issue I'm having!

On Wed, Feb 24, 2016 at 7:08 PM, Rich Signell <notifications@github.com>
wrote:

> I just tried this URL again:
>
> http://cmgdata.usgsportals.net/#module-metadata/590b5a22-b61e-11e4-b2db-00265529168c/6878f136-b61e-11e4-a8f5-00265529168c
>
> and I think I see what @emontgomery-usgs
> <https://github.com/emontgomery-usgs> is talking about. I get the empty
> map below on both chrome and firefox, even after clearing cookies and
> refreshing:
> [image: 2016-02-24_19-04-24]
> <https://cloud.githubusercontent.com/assets/1872600/13305551/ecc62cc0-db29-11e5-9202-5e92cdbe2381.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/143#issuecomment-188528314>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by kwilcox** [comment]
Must be intermittent...still working for me.  I'll check tomorrow.  

On the data note: there are a few bad data files. The best way to identify them I'd to use the portal's time sliders to limit the data window to 1960-1970 and again 2020 to 2037. There will only be a few dots visible in these periods. Click on the dots and then click "Parameter Info" to see the time range of each file.

**Comment by rsignell-usgs** [comment]
@kwilcox , yep, must be intermittant, as I just tried again and it's working again for me.

I used the sliders exactly the way you suggest to isolate the problem files, as demonstrated above:
https://github.com/USGS-CMG/usgs-cmg-portal/issues/143#issuecomment-188460619

**Comment by shane-axiom** [comment]
I verified that it wasn't working earlier and let Brian know. He deployed a quick fix, about half an hour before Kyle retested.

**Comment by rsignell-usgs** [comment]
@shane-axiom, is this quick fix a non-permanent fix, or do you just mean he found the problem quickly?

**Comment by shane-axiom** [comment]
Found and resolved the problem quickly.

**Comment by rsignell-usgs** [comment]
@shane-axiom , okay, phew!

**Comment by emontgomery-usgs** [comment]
@shane-axiom, @rsignell-usgs

Sadly it's not intermittent for me on my USGS approved laptop.  Still
doesn't work.  I have cleared my browser history and done ctrl f5, and I
still just get the whirly circle in the grey box.  This is true in both
Chrome and IE.

However, my Linux desktop has Chrome v 48.02, and the site markers etc come
right up.  So I think you might want a wider group of users on DOI PCs to
test.  I suspect it's something to do with the allowed browser
configuration that is messing up portal access.

On Wed, Feb 24, 2016 at 10:00 PM, Rich Signell <notifications@github.com>
wrote:

> @shane-axiom <https://github.com/shane-axiom> , okay, phew!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/143#issuecomment-188578782>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by emontgomery-usgs** [comment]
This file is fixed and in geoport's Data.  It tired to run collect.py to
generate a new version in CF-1.6, but got this error.:
$ python collect.py -p MONTEREY_CAN -l 4232-a.cdf --download -o
../../CF-1.6new
Traceback (most recent call last):
  File "collect.py", line 711, in <module>
    main(args.output, args.folder, args.download, projects,
os.path.realpath(args.csv_metadata_file), files, args.since)
  File "collect.py", line 402, in main
    downloaded_files = download(download_folder, project_metadata,
filesubset, since)
  File "collect.py", line 186, in download
    after=since).datasets
TypeError: __init__() got an unexpected keyword argument 'after'

Git pull says my code is up to date.

I also tried doing the whole MONTEREY_CAN folder (not just the specific
file, and deleting the existing download/MONTEREY_CAN folder (since it
doesn't seem to like to overwrite), and I still get errors related to the
init function in collect.py.

Please advise and I'll try again.   Sounds like you can update the portal
from /Data this time.


On Wed, Feb 24, 2016 at 6:15 PM, Kyle Wilcox <notifications@github.com>
wrote:

> @emontgomery-usgs <https://github.com/emontgomery-usgs> @rthieler-usgs
> <https://github.com/rthieler-usgs> This bad time data is actually in the
> raw files. The good news is that it only occurs in the MONTEREY_CAN
> project. It's a bit tricky to find, but here are the offending indexes in
> one particular file
>
>
> http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/Data/MONTEREY_CAN/4232-a.cdf.ascii?time[5110:1:5190]
>
> You can see it jumps from 2449257 to 2465116 (*15859 days!!*), then back
> down to 2449257.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/143#issuecomment-188508497>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by kwilcox** [comment]
You will need to update the thredds_crawler package

**Comment by emontgomery-usgs** [comment]
@rsignell-usgs
Back to browser versions-

I got someone else at the office to try to open the time-series data part
of the portal in internet explorer version 11.  This is the DOI default
browser.  It exhibits the same behavior as on my laptop.

We also know the time-series part doesn't work in Chrome v39, but does in
v48.

Would it be be better to have the app check the browser rev and say it
won't work in certain browser revs than to just have it fail?

On Thu, Feb 25, 2016 at 9:25 AM, Kyle Wilcox <notifications@github.com>
wrote:

> You will need to update the thredds_crawler package
>
> On Thu, Feb 25, 2016, 9:11 AM Ellyn Montgomery <notifications@github.com>
> wrote:
>
> > This file is fixed and in geoport's Data. It tired to run collect.py to
> > generate a new version in CF-1.6, but got this error.:
> > $ python collect.py -p MONTEREY_CAN -l 4232-a.cdf --download -o
> > ../../CF-1.6new
> > Traceback (most recent call last):
> > File "collect.py", line 711, in <module>
> > main(args.output, args.folder, args.download, projects,
> > os.path.realpath(args.csv_metadata_file), files, args.since)
> > File "collect.py", line 402, in main
> > downloaded_files = download(download_folder, project_metadata,
> > filesubset, since)
> > File "collect.py", line 186, in download
> > after=since).datasets
> > TypeError: __init__() got an unexpected keyword argument 'after'
> >
> > Git pull says my code is up to date.
> >
> > I also tried doing the whole MONTEREY_CAN folder (not just the specific
> > file, and deleting the existing download/MONTEREY_CAN folder (since it
> > doesn't seem to like to overwrite), and I still get errors related to the
> > init function in collect.py.
> >
> > Please advise and I'll try again. Sounds like you can update the portal
> > from /Data this time.
> >
> >
> > On Wed, Feb 24, 2016 at 6:15 PM, Kyle Wilcox <notifications@github.com>
> > wrote:
> >
> > > @emontgomery-usgs <https://github.com/emontgomery-usgs> @rthieler-usgs
> > > <https://github.com/rthieler-usgs> This bad time data is actually in
> the
> > > raw files. The good news is that it only occurs in the MONTEREY_CAN
> > > project. It's a bit tricky to find, but here are the offending indexes
> in
> > > one particular file
> > >
> > >
> > >
> >
> http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/Data/MONTEREY_CAN/4232-a.cdf.ascii?time[5110:1:5190]
> > >
> > > You can see it jumps from 2449257 to 2465116 (*15859 days!!*), then
> back
> > > down to 2449257.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/USGS-CMG/usgs-cmg-portal/issues/143#issuecomment-188508497
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Ellyn Montgomery, Oceanographer and Data Manager
> > U.S. Geological Survey
> > Woods Hole Coastal and Marine Science Center
> > 384 Woods Hole Rd., Woods Hole, MA, 02543-1598
> > (508) 457-2356
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/USGS-CMG/usgs-cmg-portal/issues/143#issuecomment-188799206
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/143#issuecomment-188807179>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by kwilcox** [comment]
@emontgomery-usgs There are issues with these files:

* 4232-a.cdf - link above
* 4233-a.cdf - http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/Data/MONTEREY_CAN/4233-a.cdf.ascii?time[14130:1:14220]
* 4241-a.cdf - http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/Data/MONTEREY_CAN/4241-a.cdf.ascii?time[3450:1:3530]
* 4263-a.cdf - http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/Data/MONTEREY_CAN/4263-a.cdf.ascii?time[13310:1:13400]

**Comment by kwilcox** [comment]
@emontgomery-usgs browser issues: https://github.com/USGS-CMG/usgs-cmg-portal/issues/169

**Comment by emontgomery-usgs** [comment]
Thanks- was going to test the rest of these, but you beat me to it.

Will let you know when I have corrected versionson /Data

On Thu, Feb 25, 2016 at 9:59 AM, Kyle Wilcox <notifications@github.com>
wrote:

> @emontgomery-usgs <https://github.com/emontgomery-usgs> There are issues
> with these files:
>
>    - 4232-a.cdf - link above
>    - 4233-a.cdf -
>    http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/Data/MONTEREY_CAN/4233-a.cdf.ascii?time[14130:1:14220]
>    - 4241-a.cdf -
>    http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/Data/MONTEREY_CAN/4241-a.cdf.ascii?time[3450:1:3530]
>    - 4263-a.cdf -
>    http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/Data/MONTEREY_CAN/4263-a.cdf.ascii?time[13310:1:13400]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/143#issuecomment-188822094>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by rsignell-usgs** [comment]
@emontgomery-usgs , I've upgraded `pyaxiom` and `thredds_crawler` on geoport, so you should be good to go with the CF conversion.

**Comment by emontgomery-usgs** [comment]
Thanks!

On Thu, Feb 25, 2016 at 10:42 AM, Rich Signell <notifications@github.com>
wrote:

> @emontgomery-usgs <https://github.com/emontgomery-usgs> , I've upgraded
> pyaxiom and thredds_crawler on geoport, so you should be good to go with
> the CF conversion.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/143#issuecomment-188846798>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by emontgomery-usgs** [comment]
@kwilcox, these files are all fixed, and are in /Data.  I was also able to
run the conversion to CF-1.6 with collect.py, so the converted files are
also available from /CF-1.6

Enjoy!

On Thu, Feb 25, 2016 at 9:59 AM, Kyle Wilcox <notifications@github.com>
wrote:

> @emontgomery-usgs <https://github.com/emontgomery-usgs> There are issues
> with these files:
>
>    - 4232-a.cdf - link above
>    - 4233-a.cdf -
>    http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/Data/MONTEREY_CAN/4233-a.cdf.ascii?time[14130:1:14220]
>    - 4241-a.cdf -
>    http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/Data/MONTEREY_CAN/4241-a.cdf.ascii?time[3450:1:3530]
>    - 4263-a.cdf -
>    http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/Data/MONTEREY_CAN/4263-a.cdf.ascii?time[13310:1:13400]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/143#issuecomment-188822094>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by akbstone** [comment]
@emontgomery-usgs, @rsignell-usgs, @kwilcox, @shane-axiom - I was able to replicate the issue you were having and found a bug that was only affecting IE. Please let me know if you're still having trouble. This checks out in IE 9, 10 and 11 for me.

http://cmgdata.usgsportals.net/#module-metadata/590b5a22-b61e-11e4-b2db-00265529168c/6878f136-b61e-11e4-a8f5-00265529168c

**Comment by emontgomery-usgs** [comment]
@akbstone, you get a big gold star!  Well done!  It now works as expected
in my IE 11.

On Thu, Feb 25, 2016 at 1:52 PM, akbstone <notifications@github.com> wrote:

> @emontgomery-usgs <https://github.com/emontgomery-usgs>, @rsignell-usgs
> <https://github.com/rsignell-usgs>, @kwilcox <https://github.com/kwilcox>,
> @shane-axiom <https://github.com/shane-axiom> - I was able to replicate
> the issue you were having and found a bug that was only affecting IE.
> Please let me know if you're still having trouble. This checks out in IE 9,
> 10 and 11 for me.
>
>
> http://cmgdata.usgsportals.net/#module-metadata/590b5a22-b61e-11e4-b2db-00265529168c/6878f136-b61e-11e4-a8f5-00265529168c
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/143#issuecomment-188926834>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by rsignell-usgs** [comment]
Version 1.0 is due today: https://github.com/USGS-CMG/usgs-cmg-portal/milestones/Version%201.0
@kwilcox, I just tried this again:
http://cmgdata.usgsportals.net/#module-metadata/590b5a22-b61e-11e4-b2db-00265529168c/6878f136-b61e-11e4-a8f5-00265529168c
and the date range is still 1960-2023.  

Can you do whatever you need to do on your end to fix this.   My understanding is that we've fixed the problem on our side, right?

**Comment by emontgomery-usgs** [comment]
@rsignell-usgs Yesterday afternoon, corrected EPIC compliant versions of
the 4 MONTEREY_CAN files Kyle pointed out were put on geoport's /Data, and
converted to CF with the results in CF-1.6.

On Fri, Feb 26, 2016 at 9:02 AM, Rich Signell <notifications@github.com>
wrote:

> Version 1.0 is due today:
> https://github.com/USGS-CMG/usgs-cmg-portal/milestones/Version%201.0
> @kwilcox <https://github.com/kwilcox>, I just tried this again:
>
> http://cmgdata.usgsportals.net/#module-metadata/590b5a22-b61e-11e4-b2db-00265529168c/6878f136-b61e-11e4-a8f5-00265529168c
> and the date range is still 1960-2023.
>
> Can you do whatever you need to do on your end to fix this. My
> understanding is that we've fixed the problem on our side, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/143#issuecomment-189290226>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by kwilcox** [comment]
Dataset Timeslider now reporting 1975-2015, all set!

**Comment by rsignell-usgs** [comment]
Time slider is reporting 2037 again on the USGS time series data.    Ugh!
@emontgomery-usgs , did we update our data with a previous older version or something?
![2016-03-21_1318](https://cloud.githubusercontent.com/assets/1872600/13927299/a2e885ba-ef67-11e5-9ac3-9cdcb729ac05.png)

**Comment by emontgomery-usgs** [comment]
Too bad that crept back in.  Last I touched anything was just before the
ver. 1 release date. If I remember right, the time slider ended in 2016 for
awhile, but I didn't notice it was back at ending in 2037.

The last specific corrections I made were to the data files in
MONTERREY_CAN.  I will check and see if the end time is 2037 in any of
these files.

On Mon, Mar 21, 2016 at 1:20 PM, Rich Signell <notifications@github.com>
wrote:

> Time slider is reporting 2037 again on the USGS time series data. Ugh!
> @emontgomery-usgs <https://github.com/emontgomery-usgs> , did we update
> our data with a previous older version or something?
> [image: 2016-03-21_1318]
> <https://cloud.githubusercontent.com/assets/1872600/13927299/a2e885ba-ef67-11e5-9ac3-9cdcb729ac05.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/143#issuecomment-199385071>
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by kwilcox** [comment]
I fixed this yesterday, leaving open to watch if it creeps back in

**Comment by rsignell-usgs** [comment]
It's fixed for me, so I'm closing this and we can reopen if it creeps back in.
