### ISSUE TITLE
Switch the CSW endpoint from geoport to gamone

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#233]
When I search for "Chincoteague" on the portal:

http://cmgdata.usgsportals.net/#module-search?p=proj3857&b=google_hybrid&page=1&tagId=&q=Chincoteague+&tags=

I get back two datasets:
![2016-12-14_10-20-17](https://cloud.githubusercontent.com/assets/1872600/21187737/037dca50-c1e7-11e6-86f9-4dc60e9e83c0.jpg)

but these are both broken, pointing to DAP endpoints that no longer exist (like 
http://geoport-dev.whoi.edu/thredds/dodsC/clay/usgs/users/nganju/chincoteague_bedelevation/00_dir_roms.ncml)

We updated our catalog at http://gamone.whoi.edu/csw , but these old entries still still remain on the portal, and I don't see our new catalog entries on the portal either.  

Is in fact the portal pointing at http://gamone.whoi.edu/csw?

**Comment by rsignell-usgs** [comment]
@kwilcox, thanks for taking a look.   I don't think the csw endpoint got switched to gamone.whoi.edu/csw because the models are all broken, looking for WMS endpoints that no longer exist.

**Comment by zdefne-usgs** [comment]
Thank you @kwilcox . Were you able to diagnose the problem? How long do you think it might take to fix it?

**Comment by rsignell-usgs** [comment]
@kwilcox chatted me: 

> tomorrow isn't looking good, i have a person in from alaska
> its not the switch that is the pain
> its making sure everything works afterwards

**Comment by zdefne-usgs** [comment]
Just checking to see if any update on this issue... Thanks!

**Comment by kwilcox** [comment]
I've been working on this for about a week and have a few updates/comments that will help to avoid this huge blocker going forward!

1. Create a standard URL schema [that won't change](https://www.w3.org/Provider/Style/URI.html). As long as you always keep these pointed at the correct server (via nginx proxy) the updates will be future proof and we can avoid downtime in case of server/hardware issues.
    * `thredds[-dev].usgs.whoi.edu`
    * `pycsw[-dev].usgs.whoi.edu`
    * `erddap[-dev].usgs.whoi.edu`

2. Create a UI on our side that shows which CSW servers are being harvested, which records were found, and where they can be found in the portal. Think of this like a harvesting dashboard. I've begun work on this and should have something to show shortly.

3. Fix the sciencebase URLs we don't have to manually add these datasets. This isn't scalable and I'd like to solve this sooner rather than later if possible. See https://github.com/USGS-CMG/usgs-cmg-portal/issues/229#issuecomment-279716074.

**Comment by rsignell-usgs** [comment]
So we do something like this on the nginx side, right?
https://gist.github.com/kwilcox/4a9568b1c5657152cf10cd0a51def1e6

and then we also need to decide whether to use WHOI domains or something else, right?

**Comment by rsignell-usgs** [comment]
@kwilcox , okay, we'll work on items 1 and 3. 

For item 1, but I don't really want to use WHOI URLs.  I'll investigate other domains. 

For item 3, we've [raised a ticket on ScienceBase](https://my.usgs.gov/jira/browse/SCIENCEBASE-6404) (you need credentials to see it)

**Comment by kwilcox** [comment]
@rsignell-usgs @zdefne-usgs We are now harvesting from the correct CSW (`gamone`) every 15 minutes! I spot checked most of the non-ScienceBase datasets and they are working correctly:

* http://cmgdata.usgsportals.net/#module-metadata/75ddbd78-eb67-3a24-a11b-06ea6800ab9e/16c6fe67-f9e0-4295-ab56-58c9e261b3c9
* http://cmgdata.usgsportals.net/#module-metadata/8f67ee8d-07c9-3bf5-ba24-fa7ad8b3a68a/3fae3fb5-3451-4122-993f-da6f17b0737d
* http://cmgdata.usgsportals.net/#module-metadata/8320fd2b-7b09-38c5-9743-91722f17ea53/9a763a8e-2170-4e76-8d0a-faa8d88d1fa9

I spent some extra time hardening the CSW system here and will have an interface to show you sometime in the near future.

**Comment by rsignell-usgs** [comment]
Woohoo!  Working again!

**Comment by rsignell-usgs** [comment]
@zdefne-usgs , can you please check and make sure all the modeling datasets that should be displayed on the portal are there and working before we close this?

**Comment by rsignell-usgs** [comment]
@kwilcox , about your suggestion to use permanent URLs for our service endpoints:  although this would be a nice thing to do in general, for the portal, it's only necessary to use a permanent URL for our CSW endpoint.

Because if you are actually discovering our data service URL endpoints via CSW , they may change at any time and the portal should still work.

Isn't that right?

**Comment by zdefne-usgs** [comment]
The ones that we recently had issues with are now working. I will make a comprehensive list of all the models that should be on the portal and check back with you if there is any issue. It will probably be better to open a new ticket in that case if necessary. Thank you @kwilcox and @rsignell-usgs

**Comment by rsignell-usgs** [comment]
@zdefne-usgs , agreed.     So closing this one.    Phew!  It's been a journey!  :champagne:

**Comment by rsignell-usgs** [comment]
@kwilcox, I'm not sure the updating every 15 minute is working.    We updated this dataset a couple of hours ago, and it's still broken: http://cmgdata.usgsportals.net/#module-metadata/0d0bc16b-90f0-3976-ae4a-9906a750497e/06e23203-0efc-4180-b13e-9dbe2fe102a1
pointing to the old URL.

**Comment by rsignell-usgs** [comment]
I just checked again, and it didn't get fixed overnight.

For the Barnegat dataset: http://cmgdata.usgsportals.net/#module-metadata/0d0bc16b-90f0-3976-ae4a-9906a750497e/a0142836-0a04-49c0-a054-6b70ff5893a9
the portal is requesting WMS images like:
http://geoport-dev.whoi.edu/thredds/wms/clay/usgs/users/zdefne/run076/00_dir_roms.ncml?LAYERS=salt&STYLES=boxfill%2Frainbow&FORMAT=image%2Fpng&TRANSPARENT=true&COLORSCALERANGE=10.17,42.95&LOGSCALE=false&ELEVATION=-0.07142857142857142&TIME=2012-11-14T00%3A00%3A00Z&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&SRS=EPSG%3A3857&BBOX=-8375052.3139844,4696291.0171875,-8296780.7970312,4774562.5341406&WIDTH=256&HEIGHT=256

But this notebook I wrote to query our CSW shows the endpoints on the portal should be reading from 
http://geoport-dev.whoi.edu/thredds/wms/clay/usgs/users/zdefne/run076/00_dir_roms2.ncml

As shown in the output of cell [4] here: 
http://nbviewer.jupyter.org/gist/rsignell-usgs/f8038f123fc3552a2bee67b2831866ee

@zdefne-usgs , this is a notebook you could run to see what our CSW thinks should be showing up on the portal.

**Comment by rsignell-usgs** [comment]
I spoke to @kwilcox  -- he will look at this tonight.

**Comment by kwilcox** [comment]
The unique identifier in your CSW changed. It went from `gov.usgs.cmg:USGS_BBLEH_SANDY_076` to `gov.usgs.cmgp:USGS_BBLEH_SANDY_076` (`cmg` to `cmgp`). As we talked about many moons ago... the unique ID can not change if you expect me to be able to update endpoints. I need that unique identifier from your CSW server to remain the same.

A new portal entry was created for the new unique identifier supplied by your CSW: http://cmgdata.usgsportals.net/#module-metadata/5f086d6e-7983-4aa3-bde9-cde441959e7a/fec63ea0-a155-4434-bf68-79b8cb6adcd4

**Comment by zdefne-usgs** [comment]
@kwilcox thanks a lot for finding out the reason for that issue. Many thanks to @rsignell-usgs for all your help. I can change the entry to cmg instead of cmgp (which might be more desirable).

**Comment by kwilcox** [comment]
I can associate the new record with the old one on my side if you want to keep the new naming convention, just let me know!

**Comment by rsignell-usgs** [comment]
@zdefne-usgs, Let's stick with CMG.

**Comment by rsignell-usgs** [comment]
@kwilcox, are we updating regularly from the CSW now, every 16 minutes?  
Was their something you had to fix?

**Comment by kwilcox** [comment]
It was and is harvesting every 15 minutes. I was associating the changes with a new dataset so you didn't notice the updates.

* 2017-02-23 15:38:29.279
* 2017-02-23 15:23:29.205
* 2017-02-23 15:08:29.158
* 2017-02-23 14:53:29.127

**Comment by zdefne-usgs** [comment]
Ok, there is still some issue with the caching . I corrected cmgp to cmg and reverted to the original ncml name 00_dir_roms.ncml instead of 00_dir_roms2.ncml, and now I get two different results for the same simulation (see below). Of course the on that refers to 00_dir_roms2.ncml is not working because that file is not there anymore. Will clear the cache manually to see if it helps. Hang on...
![croppercapture 52](https://cloud.githubusercontent.com/assets/4505315/23273639/cfecd798-f9cd-11e6-90a1-f2e8480203f5.png)

**Comment by kwilcox** [comment]
The dataset with the USGS thumbnails was the "new" one that got created. I'll delete that one and everything should work as normal.

**Comment by zdefne-usgs** [comment]
If the name or the content of the ncml file changes the portal should update automatically, should it not?
But that's not the case. Search still returns two results (which indicates that old ncml name is is still cached somewhere) and the old one still has 4 parameter panels instead of displaying 9 parameter panels as requested by the updated ncml content (which indicates that the content is still cached somewhere).

**Comment by kwilcox** [comment]
We, by design, don't delete datasets automatically. There are too many corner cases to consider. We have in the past but it has always led to a tragic and unhappy ending. If there are extra datasets added in the future that shouldn't be, I'll have to remove them manually.

**Comment by kwilcox** [comment]
I'm still seeing both datasets in the CSW (ran the notebook @rsignell-usgs provided above)

```
title:USGS Barnegat Bay Model for Hurricane Sandy : run076
identifier:gov.usgs.cmg:USGS_BBLEH_SANDY_076
modified:2017-02-23
{'scheme': 'OPeNDAP:OPeNDAP',
 'url': 'http://geoport-dev.whoi.edu/thredds/dodsC/clay/usgs/users/zdefne/run076/00_dir_roms.ncml'}
 
title:USGS Barnegat Bay Model for Hurricane Sandy : run076
identifier:gov.usgs.cmgp:USGS_BBLEH_SANDY_076
modified:2017-02-23
{'scheme': 'OPeNDAP:OPeNDAP',
 'url': 'http://geoport-dev.whoi.edu/thredds/dodsC/clay/usgs/users/zdefne/run076/00_dir_roms2.ncml'}
```

**Comment by rsignell-usgs** [comment]
Ugh, permissions problems again.    We did:
```
mkdir -m 777 /opt/docker/pycsw/force
```
at the beginning of the script that crawls the THREDDS catalogs and creates the ISO records, but the files that got created of course didn't have `777`, so could not be deleted by the Docker container.    

So for now we instead added
```
chmod -R 777 /opt/docker/pycsw/force
```
at the end of the script.

**Comment by zdefne-usgs** [comment]
:+1: 
At least one of the catalog entries is now pointing to a working model output. However, there is still a zombie with the same name still populating the catalog. Need a double tap... :)

**Comment by rsignell-usgs** [comment]
As per @kwilcox  above https://github.com/USGS-CMG/usgs-cmg-portal/issues/233#issuecomment-282098996 he needs to remove the orphan manually, I think.

**Comment by kwilcox** [comment]
Yup, removing it now

**Comment by rsignell-usgs** [comment]
Looking good now.  No dupes.  We have to fix some stuff in the NcML on our end to get sediment bed layer thickness working.
